[package]
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
description = "The Orbital Client Library"
keywords = [
    "orbital",
    "redox",
    "ui",
]
license-file = "LICENSE"
name = "orbclient"
readme = "README.md"
repository = "https://github.com/redox-os/orbclient"
version = "0.3.9"

[features]
default = []
no_std = []

[lib]
name = "orbclient"
path = "src/lib.rs"
[target.'cfg(all(not(feature="no_std"), not(target_os="redox")))'.dependencies]
sdl2 = "0.30.0"
[target.'cfg(all(not(feature="no_std"), target_os="redox"))'.dependencies]
redox_syscall = "0.1.31"
