[package]
name = "orbclient"
version = "0.3.28"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
description = "The Orbital Client Library"
documentation = "https://docs.rs/orbclient"
repository = "https://gitlab.redox-os.org/redox-os/orbclient"
readme = "README.md"
license = "MIT"
keywords = [
    "orbital",
    "redox",
    "ui",
]

[lib]
name = "orbclient"
path = "src/lib.rs"

[target.'cfg(not(target_os = "redox"))'.dependencies]
sdl2 = { version = "0.34", features = ["bundled", "static-link", "raw-window-handle"], optional = true }
sdl2-sys = { version = "0.34", features = ["bundled", "static-link"], optional = true }
libc = { version = "0.2", optional = true }
raw-window-handle = { version = "0.3", optional = true }

[target.'cfg(target_os="redox")'.dependencies]
redox_syscall = { version = "0.2.1", optional = true }

[features]
default = ["sdl2", "sdl2-sys", "libc", "raw-window-handle", "redox_syscall"]
no_std = []
