[package]
name = "orbclient"
description = "The Orbital Client Library"
repository = "https://github.com/redox-os/orbclient"
version = "0.1.6"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[lib]
name = "orbclient"
path = "src/lib.rs"

[target.i686-unknown-linux-gnu.dependencies]
sdl2 = "0.9"

[target.x86_64-unknown-linux-gnu.dependencies]
sdl2 = "0.9"

[target.i686-unknown-linux-musl.dependencies]
sdl2 = "0.9"

[target.x86_64-unknown-linux-musl.dependencies]
sdl2 = "0.9"

[target.i686-pc-windows-gnu.dependencies]
sdl2 = "0.9"

[target.x86_64-pc-windows-gnu.dependencies]
sdl2 = "0.9"

[target.i686-apple-darwin.dependencies]
sdl2 = "0.9"

[target.x86_64-apple-darwin.dependencies]
sdl2 = "0.9"
